networks:
  bots: {}

services:
  db:
    container_name: germ-db
    image: postgres:16
    networks:
      - bots
    environment:
      POSTGRES_DB: germ
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5432"]
      interval: 10s
      timeout: 9s
      retries: 6
  bot:
    container_name: germ-bot
    links: [db]
    build: .
    networks:
      - bots
    volumes:
      - ./:/src
    environment: &local-dev
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      DB_HOST: germ-db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    working_dir: /src
    command: ["gunicorn", "-c", "bot/gunicorn_config.py", "bot.main:bot", "--bind", "0.0.0.0:8000"]
    ports:
      - "8001:8000"
  test:
    container_name: germ-test
    links: [db, bot]
    build: .
    networks:
      - bots
    volumes:
      - ./:/src
    environment: *local-dev
    working_dir: /src
    command: ["pytest", "tests"]