networks:
  bots: {}

volumes:
  grafana-storage: {}
  nltk-data: { }

services:
  bot:
    networks: [bots]
    container_name: germ-bot
    depends_on:
      db-migrate:
        condition: service_completed_successfully
      jaeger-init:
        condition: service_completed_successfully
      prometheus-init:
        condition: service_completed_successfully
      test:
        condition: service_completed_successfully
    image: "germ:latest"
    ports:
      - "8001:8000"
    volumes:
      - ./:/src:rw
      - nltk-data:/root/nltk_data
    working_dir: /src
    environment: &local-dev
      HF_HOME: &hf-home ${HF_HOME:-/src/data/huggingface}
      NEO4J_AUTH: &neo4j-auth neo4j/${NEO4J_PASSWORD:-Ma9icMicr0be}
      NEO4J_HOST: &neo4j-host germ-neo4j
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_CHAT_MODEL: ${OPENAI_CHAT_MODEL}
      OPENAI_IMAGE_MODEL: ${OPENAI_IMAGE_MODEL}
      OPENAI_MINI_MODEL: ${OPENAI_MINI_MODEL}
      OPENAI_REASONING_MODEL: ${OPENAI_REASONING_MODEL}
      PG_HOST: &pg-host germ-pg
      MYSQL_PASSWORD: &mariadb-password ${POSTGRES_PASSWORD:-g01ngV1r6l}
      MYSQL_USER: &mariadb-user ${POSTGRES_USER:-germ}
      POSTGRES_PASSWORD: &pg-password ${POSTGRES_PASSWORD:-bacteria4life}
      POSTGRES_USER: &pg-user ${POSTGRES_USER:-germ}
    command: [ "scripts/app-start.sh", "germ.services.bot.main:bot_service", "8000" ]
    healthcheck:
      test: [ "CMD", "curl", "-s", "localhost:8000/healthz" ]
      interval: 60s
      timeout: 9s
      retries: 6
    logging:  # Needs rotation due to verbosity
      driver: "json-file"
      options:
        max-size: "250m"
        max-file: "3"

  data:
    networks: [bots]
    container_name: germ-data
    depends_on:
      db-migrate:
        condition: service_completed_successfully
      test:
        condition: service_completed_successfully
    image: "germ:latest"
    volumes:
      - ./:/src:rw
      - nltk-data:/root/nltk_data
    working_dir: /src
    environment: *local-dev
    command: [ "scripts/bootstrap-data.sh" ]

  db-migrate:
    networks: [bots]
    container_name: germ-db-migrate
    depends_on:
      mariadb-init:
        condition: service_completed_successfully
      neo4j-init:
        condition: service_completed_successfully
      pg-init:
        condition: service_completed_successfully
    image: "germ-db-migrate:latest"
    build:
      context: .
      dockerfile: docker/db-migrate.Dockerfile
    volumes:
      - ./:/src
    working_dir: /src
    environment:
      <<: *local-dev
      PGPASSWORD: ${POSTGRES_PASSWORD:-bacteria4life}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD:-Ma9icMicr0be}
    command: [ "scripts/db-migrate.sh" ]

  grafana:
    networks: [bots]
    container_name: germ-grafana
    depends_on:
      prometheus-init:
        condition: service_completed_successfully
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana/provisioning:/etc/grafana/provisioning
      - "grafana-storage:/var/lib/grafana"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_LOG_LEVEL=warn

  # See: https://www.jaegertracing.io/docs/1.58/spm/#architecture
  jaeger:
    networks: [bots]
    container_name: &jaeger-host germ-jaeger
    image: jaegertracing/jaeger:2.2.0
    ports:
      - "16686:16686" # UI
      - "4317:4317"   # OTLP over gRPC

  jaeger-init:
    networks: [bots]
    container_name: germ-jaeger-init
    image: "germ:latest"
    volumes:
      - ./:/src
    working_dir: /src
    environment:
      WAIT_FOR_HOST: *jaeger-host
      WAIT_FOR_PORT: 4317
    command: [ "scripts/wait-for-port-up.sh" ]

  mariadb:
    networks: [bots]
    image: mariadb:11.8
    container_name: &mariadb-host germ-mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Un71m1t6dP0w6r
      MYSQL_DATABASE: germ
      MYSQL_PASSWORD: *mariadb-password
      MYSQL_USER: *mariadb-user

  mariadb-init:
    networks: [bots]
    container_name: germ-mariadb-init
    image: "germ:latest"
    volumes:
      - ./:/src
    working_dir: /src
    environment:
      <<: *local-dev
      WAIT_FOR_HOST: *mariadb-host
      WAIT_FOR_PORT: 3306
    command: [ "scripts/wait-for-port-up.sh" ]

  models:
    networks: [bots]
    container_name: germ-models
    depends_on:
      jaeger-init:
        condition: service_completed_successfully
      prometheus-init:
        condition: service_completed_successfully
      test:
        condition: service_completed_successfully
    image: "germ:latest"
    ports:
      - "9001:9000"
    volumes:
      - ./:/src:rw
    working_dir: /src
    environment:
      HF_HOME: *hf-home
    command: [ "scripts/app-start.sh", "germ.services.models.main:model_service", "9000" ]
    healthcheck:
      test: [ "CMD", "curl", "-s", "localhost:9000/healthz" ]
      interval: 60s
      timeout: 9s
      retries: 6

  neo4j:
    networks: [bots]
    container_name: *neo4j-host
    image: neo4j:latest
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - ./database_dump/neo4j:/dump:rw
      - ./scripts/neo4j-start.sh:/neo4j-start.sh
    environment:
      NEO4J_AUTH: *neo4j-auth
    command: [ "/neo4j-start.sh" ]
    stop_grace_period: 1m

  neo4j-init:
    networks: [bots]
    container_name: germ-neo4j-init
    image: "germ:latest"
    volumes:
      - ./:/src
    working_dir: /src
    environment:
      WAIT_FOR_HOST: *neo4j-host
      WAIT_FOR_PORT: 7474
    command: [ "scripts/wait-for-port-up.sh" ]

  pg:
    networks: [bots]
    container_name: *pg-host
    image: pgvector/pgvector:pg17
    ports:
      - "5432:5432"
    volumes:
      - ./database_dump/sql:/dump:rw
      - ./scripts/pg-start.sh:/pg-start.sh
    environment:
      POSTGRES_DB: germ
      POSTGRES_PASSWORD: *pg-password
      POSTGRES_USER: *pg-user
    command: [ "/pg-start.sh" ]
    stop_grace_period: 1m

  pg-init:
    networks: [bots]
    container_name: germ-pg-init
    image: "germ:latest"
    volumes:
      - ./:/src
    working_dir: /src
    environment:
      <<: *local-dev
      WAIT_FOR_HOST: *pg-host
      WAIT_FOR_PORT: 5432
    command: [ "scripts/wait-for-port-up.sh" ]

  # See: https://www.jaegertracing.io/docs/1.58/spm/#architecture
  prometheus:
    networks: [bots]
    container_name: &prometheus-host germ-prometheus
    image: prom/prometheus:v2.52.0
    ports:
      - '9090:9090'
    volumes:
      - ./data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      #- --log.level=debug
      - --log.level=warn

  prometheus-init:
    networks: [bots]
    container_name: germ-prometheus-init
    image: "germ:latest"
    volumes:
      - ./:/src
    working_dir: /src
    environment:
      WAIT_FOR_HOST: *prometheus-host
      WAIT_FOR_PORT: 9090
    command: [ "scripts/wait-for-port-up.sh" ]

  redis:
    networks: [bots]
    container_name: germ-redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./database_dump/redis:/data:rw
      - ./scripts/redis-start.sh:/redis-start.sh
    entrypoint: [ "/redis-start.sh" ]
    stop_grace_period: 1m

  test:
    networks: [bots]
    container_name: germ-test
    depends_on:
      venv:
        condition: service_completed_successfully
    image: "germ:latest"
    volumes:
      - ./:/src
    working_dir: /src
    environment:
      <<: *local-dev
      SKIP_INTEGRATION_TESTS: ${SKIP_INTEGRATION_TESTS:-true}
      SKIP_TESTS: ${SKIP_TESTS:-true}
    command: ["tests/run.sh"]

  venv:
    networks: [bots]
    container_name: germ-venv
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    image: "germ:latest"
    volumes:
      - ./:/src
    working_dir: /src
    command: [ "scripts/venv.sh" ]
