services:
  bot:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8001:8000"
  test:
    build: .
    command: ["pytest", "tests"]
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
