INSERT INTO struct_type (group_name, att_pub_ident, att_value)
VALUES
      ('text_block_type', 'code', 'Code')
    , ('text_block_type', 'paragraph', 'Paragraph')
    , ('text_block_type', 'sentence', 'Sentence')

    /*
    Based on UD multi-classifier labels
    */
    , ('text_token_adjgrad_type', 'O', 'O')
    , ('text_token_adjgrad_type', 'no', 'no')
    , ('text_token_adjgrad_type', 'yes', 'yes')

    , ('text_token_adjpos_type', 'O', 'O')
    , ('text_token_adjpos_type', 'attributive', 'attributive')
    , ('text_token_adjpos_type', 'postpositive', 'postpositive')
    , ('text_token_adjpos_type', 'predicative', 'predicative')

    , ('text_token_adjtype_type', 'O', 'O')
    , ('text_token_adjtype_type', 'age', 'age')
    , ('text_token_adjtype_type', 'color', 'color')
    , ('text_token_adjtype_type', 'limiting', 'limiting')
    , ('text_token_adjtype_type', 'material', 'material')
    , ('text_token_adjtype_type', 'origin', 'origin')
    , ('text_token_adjtype_type', 'purpose', 'purpose')
    , ('text_token_adjtype_type', 'quality', 'quality')
    , ('text_token_adjtype_type', 'quantifying', 'quantifying')
    , ('text_token_adjtype_type', 'relational', 'relational')
    , ('text_token_adjtype_type', 'shape', 'shape')
    , ('text_token_adjtype_type', 'size', 'size')

    , ('text_token_advtype_type', 'O', 'O')
    , ('text_token_advtype_type', 'conjunctive', 'conjunctive')
    , ('text_token_advtype_type', 'degree', 'degree')
    , ('text_token_advtype_type', 'disjunct', 'disjunct')
    , ('text_token_advtype_type', 'focusing', 'focusing')
    , ('text_token_advtype_type', 'frequency', 'frequency')
    , ('text_token_advtype_type', 'manner', 'manner')
    , ('text_token_advtype_type', 'modal', 'modal')
    , ('text_token_advtype_type', 'negation', 'negation')
    , ('text_token_advtype_type', 'place', 'place')
    , ('text_token_advtype_type', 'time', 'time')

    , ('text_token_case_type', 'Acc', 'Acc')
    , ('text_token_case_type', 'Nom', 'Nom')
    , ('text_token_case_type', 'O', 'O')

    , ('text_token_definite_type', 'Def', 'Def')
    , ('text_token_definite_type', 'Ind', 'Ind')
    , ('text_token_definite_type', 'O', 'O')

    , ('text_token_degree_type', 'Cmp', 'Cmp')
    , ('text_token_degree_type', 'O', 'O')
    , ('text_token_degree_type', 'Pos', 'Pos')
    , ('text_token_degree_type', 'Sup', 'Sup')

    , ('text_token_deprel_type', 'acl', 'acl')
    , ('text_token_deprel_type', 'acl:relcl', 'acl:relcl')
    , ('text_token_deprel_type', 'advcl', 'advcl')
    , ('text_token_deprel_type', 'advmod', 'advmod')
    , ('text_token_deprel_type', 'amod', 'amod')
    , ('text_token_deprel_type', 'appos', 'appos')
    , ('text_token_deprel_type', 'aux', 'aux')
    , ('text_token_deprel_type', 'aux:pass', 'aux:pass')
    , ('text_token_deprel_type', 'case', 'case')
    , ('text_token_deprel_type', 'cc', 'cc')
    , ('text_token_deprel_type', 'cc:preconj', 'cc:preconj')
    , ('text_token_deprel_type', 'ccomp', 'ccomp')
    , ('text_token_deprel_type', 'compound', 'compound')
    , ('text_token_deprel_type', 'compound:prt', 'compound:prt')
    , ('text_token_deprel_type', 'conj', 'conj')
    , ('text_token_deprel_type', 'cop', 'cop')
    , ('text_token_deprel_type', 'csubj', 'csubj')
    , ('text_token_deprel_type', 'det', 'det')
    , ('text_token_deprel_type', 'det:predet', 'det:predet')
    , ('text_token_deprel_type', 'discourse', 'discourse')
    , ('text_token_deprel_type', 'expl', 'expl')
    , ('text_token_deprel_type', 'fixed', 'fixed')
    , ('text_token_deprel_type', 'flat', 'flat')
    , ('text_token_deprel_type', 'iobj', 'iobj')
    , ('text_token_deprel_type', 'list', 'list')
    , ('text_token_deprel_type', 'mark', 'mark')
    , ('text_token_deprel_type', 'nmod', 'nmod')
    , ('text_token_deprel_type', 'nmod:npmod', 'nmod:npmod')
    , ('text_token_deprel_type', 'nmod:poss', 'nmod:poss')
    , ('text_token_deprel_type', 'nmod:tmod', 'nmod:tmod')
    , ('text_token_deprel_type', 'nsubj', 'iobj')
    , ('text_token_deprel_type', 'nsubj:pass', 'nsubj:pass')
    , ('text_token_deprel_type', 'nummod', 'nummod')
    , ('text_token_deprel_type', 'obj', 'obj')
    , ('text_token_deprel_type', 'obl', 'obl')
    , ('text_token_deprel_type', 'obl:npmod', 'obl:npmod')
    , ('text_token_deprel_type', 'obl:tmod', 'obl:tmod')
    , ('text_token_deprel_type', 'parataxis', 'parataxis')
    , ('text_token_deprel_type', 'punct', 'punct')
    , ('text_token_deprel_type', 'root', 'root')
    , ('text_token_deprel_type', 'vocative', 'vocative')
    , ('text_token_deprel_type', 'xcomp', 'xcomp')

    , ('text_token_gender_type', 'Fem', 'Fem')
    , ('text_token_gender_type', 'Masc', 'Masc')
    , ('text_token_gender_type', 'Neut', 'Neut')
    , ('text_token_gender_type', 'O', 'O')

    , ('text_token_mood_type', 'Imp', 'Imp')
    , ('text_token_mood_type', 'Ind', 'Ind')
    , ('text_token_mood_type', 'O', 'O')

    , ('text_token_numtype_type', 'Card', 'Card')
    , ('text_token_numtype_type', 'Mult', 'Mult')
    , ('text_token_numtype_type', 'O', 'O')
    , ('text_token_numtype_type', 'Ord', 'Ord')

    , ('text_token_number_type', 'O', 'O')
    , ('text_token_number_type', 'Plur', 'Plur')
    , ('text_token_number_type', 'Sing', 'Sing')

    , ('text_token_person_type', '1', '1')
    , ('text_token_person_type', '2', '2')
    , ('text_token_person_type', '3', '3')
    , ('text_token_person_type', 'O', 'O')

    , ('text_token_pos_type', 'ADJ', 'ADJ')
    , ('text_token_pos_type', 'ADP', 'ADP')
    , ('text_token_pos_type', 'ADV', 'ADV')
    , ('text_token_pos_type', 'AUX', 'AUX')
    , ('text_token_pos_type', 'CCONJ', 'CCONJ')
    , ('text_token_pos_type', 'DET', 'DET')
    , ('text_token_pos_type', 'INTJ', 'INTJ')
    , ('text_token_pos_type', 'NOUN', 'NOUN')
    , ('text_token_pos_type', 'NUM', 'NUM')
    , ('text_token_pos_type', 'PART', 'PART')
    , ('text_token_pos_type', 'PRON', 'PRON')
    , ('text_token_pos_type', 'PROPN', 'PROPN')
    , ('text_token_pos_type', 'PUNCT', 'PUNCT')
    , ('text_token_pos_type', 'SCONJ', 'SCONJ')
    , ('text_token_pos_type', 'SYM', 'SYM')
    , ('text_token_pos_type', 'VERB', 'VERB')
    , ('text_token_pos_type', 'X', 'X')

    , ('text_token_prontype_type', 'Art', 'Art')
    , ('text_token_prontype_type', 'Dem', 'Dem')
    , ('text_token_prontype_type', 'Int', 'Int')
    , ('text_token_prontype_type', 'O', 'O')
    , ('text_token_prontype_type', 'Prs', 'Prs')
    , ('text_token_prontype_type', 'Rel', 'Rel')

    , ('text_token_tense_type', 'O', 'O')
    , ('text_token_tense_type', 'Past', 'Past')
    , ('text_token_tense_type', 'Pres', 'Pres')

    , ('text_token_verbform_type', 'Fin', 'Fin')
    , ('text_token_verbform_type', 'Ger', 'Ger')
    , ('text_token_verbform_type', 'Inf', 'Inf')
    , ('text_token_verbform_type', 'O', 'O')
    , ('text_token_verbform_type', 'Part', 'Part')

    , ('text_token_xpos_type', '''''', '''''')
    , ('text_token_xpos_type', '$', '$')
    , ('text_token_xpos_type', ',', ',')
    , ('text_token_xpos_type', '-LRB-', '-LRB-')
    , ('text_token_xpos_type', '-RRB-', '-RRB-')
    , ('text_token_xpos_type', '.', '.')
    , ('text_token_xpos_type', ':', ':')
    , ('text_token_xpos_type', 'ADD', 'ADD')
    , ('text_token_xpos_type', 'CC', 'CC')
    , ('text_token_xpos_type', 'CD', 'CD')
    , ('text_token_xpos_type', 'DT', 'DT')
    , ('text_token_xpos_type', 'EX', 'EX')
    , ('text_token_xpos_type', 'FW', 'FW')
    , ('text_token_xpos_type', 'HYPH', 'HYPG')
    , ('text_token_xpos_type', 'IN', 'IN')
    , ('text_token_xpos_type', 'JJ', 'JJ')
    , ('text_token_xpos_type', 'JJR', 'JJR')
    , ('text_token_xpos_type', 'JJS', 'JJS')
    , ('text_token_xpos_type', 'LS', 'LS')
    , ('text_token_xpos_type', 'MD', 'MD')
    , ('text_token_xpos_type', 'NFP', 'NFP')
    , ('text_token_xpos_type', 'NN', 'NN')
    , ('text_token_xpos_type', 'NNP', 'NNP')
    , ('text_token_xpos_type', 'NNPS', 'NNPS')
    , ('text_token_xpos_type', 'NNS', 'NNS')
    , ('text_token_xpos_type', 'PDT', 'PDT')
    , ('text_token_xpos_type', 'POS', 'POS')
    , ('text_token_xpos_type', 'PRP$', 'PRP$')
    , ('text_token_xpos_type', 'PRP', 'PRP')
    , ('text_token_xpos_type', 'RB', 'RB')
    , ('text_token_xpos_type', 'RBR', 'RBR')
    , ('text_token_xpos_type', 'RBS', 'RBS')
    , ('text_token_xpos_type', 'RP', 'RP')
    , ('text_token_xpos_type', 'SYM', 'SYM')
    , ('text_token_xpos_type', 'TO', 'TO')
    , ('text_token_xpos_type', 'UH', 'UH')
    , ('text_token_xpos_type', 'VB', 'VB')
    , ('text_token_xpos_type', 'VBD', 'VBD')
    , ('text_token_xpos_type', 'VBG', 'VBG')
    , ('text_token_xpos_type', 'VBN', 'VBN')
    , ('text_token_xpos_type', 'VBP', 'VBP')
    , ('text_token_xpos_type', 'VBZ', 'VBZ')
    , ('text_token_xpos_type', 'WDT', 'WDT')
    , ('text_token_xpos_type', 'WP$', 'WP$')
    , ('text_token_xpos_type', 'WP', 'WP')
    , ('text_token_xpos_type', 'WRB', 'WRB')
    , ('text_token_xpos_type', '``', '``')
ON CONFLICT (group_name, att_pub_ident)
DO NOTHING;
