DEFAULT_CHAT_MODEL = 'gpt-4o'
DEFAULT_MINI_MODEL = "gpt-4o-mini"
DEFAULT_IMAGE_MODEL = 'dall-e-3'
DEFAULT_ROUTING_MODEL = DEFAULT_MINI_MODEL
ENABLED_CHAT_MODELS = (
    DEFAULT_CHAT_MODEL,
)
ENABLED_IMAGE_MODELS = (
    DEFAULT_IMAGE_MODEL,
)
HTTPX_TIMEOUT = 30
