receivers:
  otlp:
    protocols:
      http:
        endpoint: "germ-otel-collector:4318"

exporters:
  prometheus:
    endpoint: "germ-otel-collector:8889"

  otlp:
    endpoint: germ-jaeger:4317
    tls:
      insecure: true

connectors:
  spanmetrics:

processors:
  batch:
    timeout: 10s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [spanmetrics, otlp]
    # The exporter name in this pipeline must match the spanmetrics.metrics_exporter name.
    # The receiver is just a dummy and never used; added to pass validation requiring at least one receiver in a pipeline.
    metrics/spanmetrics:
      receivers: [spanmetrics]
      exporters: [prometheus]