global:
  scrape_interval:     60s
  evaluation_interval: 60s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: germ-bot
    static_configs:
      - targets: ['germ-bot:8000']
  - job_name: germ-models
    static_configs:
      - targets: ['germ-models:9000']
