
default_entity_types = [
    "activity",
    "apparel",
    "area",
    "capability",
    "concept",
    "container",
    "currency",
    "date or time",
    "device",
    "distance",
    "duration",
    "event",
    "fauna",
    "flora",
    "initiative or objective",
    "instrument",
    "job or profession",
    "language",
    "material or substance",
    "measurement",
    "media",
    "organization",
    "person",
    "phenomenon",
    "place",
    "quantity",
    "ritual or tradition",
    "road",
    "sensation",
    "structure",
    "terrain",
    "trait",
    "vehicle"
    "weight"
]
