name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cat > .env <<EOF
          OPENAI_API_KEY=$OPENAI_API_KEY
          POSTGRES_USER=germ
          POSTGRES_PASSWORD=bacteria4life
          EOF
          docker-compose run test
